import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface SeedMediaData {
  title: string;
  type: string; // "MOVIE" or "TV_SHOW"
  director?: string;
  budget?: number;
  location?: string;
  duration?: number;
  year?: number;
  genre?: string; // Genre as string
  rating?: number;
  description?: string;
  language?: string;
  posterUrl?: string;
}

const sampleData: SeedMediaData[] = [
  {
    title: "The Shawshank Redemption",
    type: "MOVIE",
    director: "Frank Darabont",
    budget: 25000000,
    location: "NEW_YORK",
    duration: 142,
    year: 1994,
    genre: "DRAMA",
    rating: 9.3,
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
  },
  {
    title: "The Godfather",
    type: "MOVIE",
    director: "Francis Ford Coppola",
    budget: 6000000,
    location: "ROME",
    duration: 175,
    year: 1972,
    genre: "CRIME",
    rating: 9.2,
    description: "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
  },
  {
    title: "Breaking Bad",
    type: "TV_SHOW",
    director: "Vince Gilligan",
    budget: 3000000,
    location: "SYDNEY",
    duration: 47,
    year: 2008,
    genre: "CRIME",
    rating: 9.5,
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5MWZiNWM1ZWQyXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg",
  },
  {
    title: "Pulp Fiction",
    type: "MOVIE",
    director: "Quentin Tarantino",
    budget: 8000000,
    location: "VANCOUVER",
    duration: 154,
    year: 1994,
    genre: "CRIME",
    rating: 8.9,
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
  },
  {
    title: "Stranger Things",
    type: "TV_SHOW",
    director: "The Duffer Brothers",
    budget: 6000000,
    location: "MUMBAI",
    duration: 51,
    year: 2016,
    genre: "SCIENCE_FICTION",
    rating: 8.7,
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
  },
  {
    title: "Inception",
    type: "MOVIE",
    director: "Christopher Nolan",
    budget: 160000000,
    location: "TOKYO",
    duration: 148,
    year: 2010,
    genre: "SCIENCE_FICTION",
    rating: 8.8,
    description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
  },
  {
    title: "The Dark Knight",
    type: "MOVIE",
    director: "Christopher Nolan",
    budget: 185000000,
    location: "LONDON",
    duration: 152,
    year: 2008,
    genre: "ACTION",
    rating: 9.0,
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_.jpg",
  },
  {
    title: "Game of Thrones",
    type: "TV_SHOW",
    director: "David Benioff",
    budget: 15000000,
    location: "BERLIN",
    duration: 57,
    year: 2011,
    genre: "FANTASY",
    rating: 9.3,
    description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg",
  },
  {
    title: "The Matrix",
    type: "MOVIE",
    director: "Lana Wachowski",
    budget: 63000000,
    location: "LOS_ANGELES",
    duration: 136,
    year: 1999,
    genre: "SCIENCE_FICTION",
    rating: 8.7,
    description: "A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
  },
  {
    title: "Friends",
    type: "TV_SHOW",
    director: "David Crane",
    budget: 1000000,
    location: "NEW_YORK",
    duration: 22,
    year: 1994,
    genre: "COMEDY",
    rating: 8.9,
    description: "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
  },
  {
    title: "La La Land",
    type: "MOVIE",
    director: "Damien Chazelle",
    budget: 30000000,
    location: "LOS_ANGELES",
    duration: 128,
    year: 2016,
    genre: "ROMANCE",
    rating: 8.0,
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_.jpg",
  },
  {
    title: "Parasite",
    type: "MOVIE",
    director: "Bong Joon-ho",
    budget: 11400000,
    location: "SEOUL",
    duration: 132,
    year: 2019,
    genre: "THRILLER",
    rating: 8.6,
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    language: "KOREAN",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
  },
  {
    title: "The Crown",
    type: "TV_SHOW",
    director: "Peter Morgan",
    budget: 13000000,
    location: "LONDON",
    duration: 58,
    year: 2016,
    genre: "DRAMA",
    rating: 8.7,
    description: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZmY0MzBlYzAtNTRiYi00OWQ2LWFmZjUtOWRkMDIxNWU3NzI3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg",
  },
  {
    title: "Amélie",
    type: "MOVIE",
    director: "Jean-Pierre Jeunet",
    budget: 10000000,
    location: "PARIS",
    duration: 122,
    year: 2001,
    genre: "ROMANCE",
    rating: 8.3,
    description: "Amélie, an innocent and naive girl in Paris, with her own sense of justice, decides to help those around her and along the way, discovers love.",
    language: "FRENCH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNDg4NjM1YjMtYTNhZC00YzVmLThmZTctMjY2Yzk0ZDEzNjA3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
  },
  {
    title: "Money Heist",
    type: "TV_SHOW",
    director: "Álex Pina",
    budget: 3000000,
    location: "MADRID",
    duration: 50,
    year: 2017,
    genre: "CRIME",
    rating: 8.2,
    description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    language: "SPANISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BODI0ZTliYzAtNDA0Yy00OTY2LTliNmQtZTE0MzQxNWNhMWU0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
  },
  {
    title: "Spirited Away",
    type: "MOVIE",
    director: "Hayao Miyazaki",
    budget: 15000000,
    location: "TOKYO",
    duration: 125,
    year: 2001,
    genre: "ANIMATION",
    rating: 8.6,
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.",
    language: "JAPANESE",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNTlhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
  },
  {
    title: "The Witcher",
    type: "TV_SHOW",
    director: "Lauren Schmidt Hissrich",
    budget: 8000000,
    location: "BERLIN",
    duration: 60,
    year: 2019,
    genre: "FANTASY",
    rating: 8.0,
    description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BN2FiOWU4YzYtMzZiOS00MzcyLTlkOGEtOTgwZmEwMzAxMzA3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
  },
  {
    title: "Coco",
    type: "MOVIE",
    director: "Lee Unkrich",
    budget: 175000000,
    location: "MADRID",
    duration: 105,
    year: 2017,
    genre: "ANIMATION",
    rating: 8.4,
    description: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    language: "SPANISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3NzAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_.jpg",
  },
  {
    title: "The Handmaid's Tale",
    type: "TV_SHOW",
    director: "Bruce Miller",
    budget: 5000000,
    location: "VANCOUVER",
    duration: 60,
    year: 2017,
    genre: "DRAMA",
    rating: 8.4,
    description: "Set in a dystopian future, a woman is forced to live as a concubine under a fundamentalist theocratic dictatorship.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZjRlZDIyNDMtYzU1Zi00MzM4LTlkMWUtNzBlN2Y2Y2IxYzM5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
  },
  {
    title: "The Grand Budapest Hotel",
    type: "MOVIE",
    director: "Wes Anderson",
    budget: 25000000,
    location: "BERLIN",
    duration: 99,
    year: 2014,
    genre: "COMEDY",
    rating: 8.1,
    description: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_.jpg",
  },
  {
    title: "Narcos",
    type: "TV_SHOW",
    director: "Carlo Bernard",
    budget: 2500000,
    location: "MADRID",
    duration: 50,
    year: 2015,
    genre: "CRIME",
    rating: 8.8,
    description: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.",
    language: "SPANISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNmFjODA3YzItM2I0ZC00MzUyLTgxNzUtNjM2N2QxNzBmOTBkXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg",
  },
  {
    title: "The Lion King",
    type: "MOVIE",
    director: "Roger Allers",
    budget: 45000000,
    location: "LOS_ANGELES",
    duration: 88,
    year: 1994,
    genre: "ANIMATION",
    rating: 8.5,
    description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_.jpg",
  },
  {
    title: "The Mandalorian",
    type: "TV_SHOW",
    director: "Jon Favreau",
    budget: 15000000,
    location: "LOS_ANGELES",
    duration: 40,
    year: 2019,
    genre: "SCIENCE_FICTION",
    rating: 8.7,
    description: "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZjRlZDIyNDMtYzU1Zi00MzM4LTlkMWUtNzBlN2Y2Y2IxYzM5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
  },
  {
    title: "The Silence of the Lambs",
    type: "MOVIE",
    director: "Jonathan Demme",
    budget: 19000000,
    location: "NEW_YORK",
    duration: 118,
    year: 1991,
    genre: "THRILLER",
    rating: 8.6,
    description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
  },
  {
    title: "Fleabag",
    type: "TV_SHOW",
    director: "Phoebe Waller-Bridge",
    budget: 1000000,
    location: "LONDON",
    duration: 26,
    year: 2016,
    genre: "COMEDY",
    rating: 8.7,
    description: "A comedy series adapted from the award-winning play about a young woman trying to cope with life in London whilst coming to terms with a recent tragedy.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjA4MzQ0ODgxNV5BMl5BanBnXkFtZTgwOTQ1OTI0NzM@._V1_.jpg",
  },
  {
    title: "Pan's Labyrinth",
    type: "MOVIE",
    director: "Guillermo del Toro",
    budget: 19000000,
    location: "MADRID",
    duration: 118,
    year: 2006,
    genre: "FANTASY",
    rating: 8.2,
    description: "In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
    language: "SPANISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNzJlMjI2NjEtY2FmNy00ZTE0LWJjYWEtZDg0YmY1ZDBlNmEyXkEyXkFqcGdeQXVyOTk3NTc2MzE@._V1_.jpg",
  },
  {
    title: "The Queen's Gambit",
    type: "TV_SHOW",
    director: "Scott Frank",
    budget: 7000000,
    location: "BERLIN",
    duration: 60,
    year: 2020,
    genre: "DRAMA",
    rating: 8.6,
    description: "Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BM2EwMmRhMmUtMzBmMS00ZDQ3LTg4OGEtNjlkODk3ZTMxMmJlXkEyXkFqcGdeQXVyMjM5ODk1NDU@._V1_.jpg",
  },
  {
    title: "Life is Beautiful",
    type: "MOVIE",
    director: "Roberto Benigni",
    budget: 20000000,
    location: "ROME",
    duration: 116,
    year: 1997,
    genre: "COMEDY",
    rating: 8.6,
    description: "When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.",
    language: "ITALIAN",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
  },
  {
    title: "Dark",
    type: "TV_SHOW",
    director: "Baran bo Odar",
    budget: 4000000,
    location: "BERLIN",
    duration: 60,
    year: 2017,
    genre: "MYSTERY",
    rating: 8.7,
    description: "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.",
    language: "GERMAN",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOTk2NzUyOTctZDdlMS00MDJlLTgzNTEyNzQzYzE2ZGRmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
  },
  {
    title: "Crouching Tiger, Hidden Dragon",
    type: "MOVIE",
    director: "Ang Lee",
    budget: 17000000,
    location: "BEIJING",
    duration: 120,
    year: 2000,
    genre: "ACTION",
    rating: 7.8,
    description: "A young Chinese warrior steals a sword from a famed swordsman and then escapes into a world of romantic adventure with a mysterious man in the frontier of the nation.",
    language: "CHINESE",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNDdhMzMxOTctNDMyNS00NTU5LTg3MzMtYjEwODg3ODg0ZGVkXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
  },
  {
    title: "Sacred Games",
    type: "TV_SHOW",
    director: "Vikramaditya Motwane",
    budget: 2000000,
    location: "MUMBAI",
    duration: 50,
    year: 2018,
    genre: "CRIME",
    rating: 8.4,
    description: "A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.",
    language: "HINDI",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjJlMjJlMzYtNWU5Yy00N2MwLTg1MDItODgzMmM3MmRiNWQwXkEyXkFqcGdeQXVyNDY4NjAxNTc@._V1_.jpg",
  },
  {
    title: "The Hunt",
    type: "MOVIE",
    director: "Thomas Vinterberg",
    budget: 3000000,
    location: "BERLIN",
    duration: 115,
    year: 2012,
    genre: "DRAMA",
    rating: 8.3,
    description: "A teacher lives a lonely life, all the while struggling over his son's custody. His life slowly gets better as he finds love and receives good news from his son, but his new luck is about to be brutally shattered by an innocent little lie.",
    language: "GERMAN",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTg2NDg3ODg4NF5BMl5BanBnXkFtZTcwNzk3NTc3Nw@@._V1_.jpg",
  },
  {
    title: "The Boys",
    type: "TV_SHOW",
    director: "Eric Kripke",
    budget: 11000000,
    location: "VANCOUVER",
    duration: 60,
    year: 2019,
    genre: "ACTION",
    rating: 8.7,
    description: "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNGEyOGJiNWEtMTgwMi00ODk4LTk1MmYtYzQ0MDAxYTZkYjI4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
  },
  {
    title: "The Lord of the Rings",
    type: "MOVIE",
    director: "Peter Jackson",
    budget: 93000000,
    location: "MOSCOW",
    duration: 178,
    year: 2001,
    genre: "ADVENTURE",
    rating: 8.9,
    description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg",
  },
  {
    title: "The Pianist",
    type: "MOVIE",
    director: "Roman Polanski",
    budget: 35000000,
    location: "PARIS",
    duration: 150,
    year: 2002,
    genre: "BIOGRAPHY",
    rating: 8.5,
    description: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktYTA1NC00MDQ2LWEzOGUtNTY3NWJkODJmZGU3XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
  },
  {
    title: "March of the Penguins",
    type: "MOVIE",
    director: "Luc Jacquet",
    budget: 8000000,
    location: "SYDNEY",
    duration: 80,
    year: 2005,
    genre: "DOCUMENTARY",
    rating: 7.6,
    description: "In the Antarctic, every March since the beginning of time, the quest begins to find the perfect mate and start a family.",
    language: "FRENCH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTc1MjM0OTc1M15BMl5BanBnXkFtZTcwNzUyMjgyMQ@@._V1_.jpg",
  },
  {
    title: "The Sound of Music",
    type: "MOVIE",
    director: "Robert Wise",
    budget: 8200000,
    location: "ROME",
    duration: 172,
    year: 1965,
    genre: "FAMILY",
    rating: 8.0,
    description: "A woman leaves an Austrian convent to become a governess to the children of a Naval officer widower.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BODIxNjhkYjEtYzUyMi00YTNjLWE1YjktNjAyYzIzOWY3YWIwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
  },
  {
    title: "The Exorcist",
    type: "MOVIE",
    director: "William Friedkin",
    budget: 12000000,
    location: "NEW_YORK",
    duration: 122,
    year: 1973,
    genre: "HORROR",
    rating: 8.0,
    description: "When a 12-year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYjhmMGMxZDYtMTkyNy00YWVmLTgyYmUtYTU3ZjcwNTBjN2I5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
  },
  {
    title: "Amadeus",
    type: "MOVIE",
    director: "Milos Forman",
    budget: 18000000,
    location: "BERLIN",
    duration: 160,
    year: 1984,
    genre: "MUSIC",
    rating: 8.3,
    description: "The life, success and troubles of Wolfgang Amadeus Mozart, as told by Antonio Salieri, the contemporaneous composer who was insanely jealous of Mozart's talent and claimed to have murdered him.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNWJlNzUzNGMtYTAwMS00ZjI2LWFmNWQtODcxNWUxZmM2ZjM4XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
  },
  {
    title: "Saving Private Ryan",
    type: "MOVIE",
    director: "Steven Spielberg",
    budget: 70000000,
    location: "LONDON",
    duration: 169,
    year: 1998,
    genre: "WAR",
    rating: 8.6,
    description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
    language: "ENGLISH",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg",
  },
  {
    title: "The Good, the Bad and the Ugly",
    type: "MOVIE",
    director: "Sergio Leone",
    budget: 1200000,
    location: "MADRID",
    duration: 161,
    year: 1966,
    genre: "WESTERN",
    rating: 8.8,
    description: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
    language: "ITALIAN",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_.jpg",
  },
  {
    title: "The Russian Ark",
    type: "MOVIE",
    director: "Alexander Sokurov",
    budget: 2500000,
    location: "MOSCOW",
    duration: 96,
    year: 2002,
    genre: "HISTORY",
    rating: 7.3,
    description: "A 19th century French aristocrat, on a tour of the Hermitage, reflects on Russian society and its Europeanization.",
    language: "RUSSIAN",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTI3MjE1NDg1NF5BMl5BanBnXkFtZTcwOTQzOTUyMQ@@._V1_.jpg",
  },
  {
    title: "The Kite Runner",
    type: "MOVIE",
    director: "Marc Forster",
    budget: 20000000,
    location: "BEIJING",
    duration: 128,
    year: 2007,
    genre: "DRAMA",
    rating: 7.6,
    description: "After spending years in California, Amir returns to his homeland in Afghanistan to help his old friend Hassan, whose son is in trouble.",
    language: "ARABIC",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BODcyNjE4OTU0Ml5BMl5BanBnXkFtZTcwNjg2NDUyMQ@@._V1_.jpg",
  },
  {
    title: "City of God",
    type: "MOVIE",
    director: "Fernando Meirelles",
    budget: 3300000,
    location: "SEOUL",
    duration: 130,
    year: 2002,
    genre: "CRIME",
    rating: 8.6,
    description: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    language: "PORTUGUESE",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMGU5OWEwZDItNmNkMC00NzZmLTk1YTctNzVhZTJjMTNlZTVmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
  },
];

async function main(): Promise<void> {
  console.log("Starting database seeding...");

  for (const media of sampleData) {
    const result = await prisma.media.create({
      data: media,
    });
    console.log(`Created media: ${result.title} (${result.type})`);
  }

  console.log("Database seeding completed!");
}

main()
  .catch((e) => {
    console.error("Error during seeding:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
